"""Create questions table

Revision ID: 0f59ef0a17f8
Revises: 
Create Date: 2025-04-25 12:12:21.284148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f59ef0a17f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_number', sa.String(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('round', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('question', sa.String(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_air_date'), 'questions', ['air_date'], unique=False)
    op.create_index(op.f('ix_questions_answer'), 'questions', ['answer'], unique=False)
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_question'), 'questions', ['question'], unique=True)
    op.create_index(op.f('ix_questions_round'), 'questions', ['round'], unique=False)
    op.create_index(op.f('ix_questions_show_number'), 'questions', ['show_number'], unique=False)
    op.create_index(op.f('ix_questions_value'), 'questions', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_value'), table_name='questions')
    op.drop_index(op.f('ix_questions_show_number'), table_name='questions')
    op.drop_index(op.f('ix_questions_round'), table_name='questions')
    op.drop_index(op.f('ix_questions_question'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.drop_index(op.f('ix_questions_answer'), table_name='questions')
    op.drop_index(op.f('ix_questions_air_date'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
