"""Change Question value type

Revision ID: 6620a75fb828
Revises: 0f59ef0a17f8
Create Date: 2025-04-25 13:06:04.389654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6620a75fb828'
down_revision: Union[str, None] = '0f59ef0a17f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE questions SET value = '0' WHERE value IS NULL OR value = '';")
    # Use PostgreSQL's USING clause to explicitly cast the values, removing $ and , characters
    op.execute("ALTER TABLE questions ALTER COLUMN value TYPE INTEGER USING (CASE WHEN value ~ E'^\\\\$?[0-9,]+$' THEN REPLACE(REPLACE(value, '$', ''), ',', '')::integer ELSE 0 END);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'value',
                    existing_type=sa.Integer(),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
